### ISSUE TITLE
Only copy's content of changed fields. (Craft 3.4.*)

### ISSUE THREAD

**Issue by RamonArno** [Goldinteractive/craft3-sitecopy#12] opened 2020-02-18 09:54 UTC
Worked fine on Craft 3.3, after updating to craft 3.4.5 the plugin no longer works as intended.

The content no longer gets copy's from one site to another on safe. Only when you change a field's content and then save the page that one field content gets copied.

**Comment by RamonArno** [comment] 2020-02-27 15:14
Hey, 

any feedback on this?

**Comment by lukasNo1** [comment] 2020-02-27 15:21
Hey RamonArno

We gonna investigate this in the course of the next week.

The problem is, as of craft 3.4, craft only sends the newly changed fields on the save request, instead of like before all fields of the entry.

So we likely need to adjust the plugin to read the data from the model instead of the request.

**Comment by lukasNo1** [comment] 2020-03-02 12:02
This is fixed in the new release 0.5.1

**Closed as completed by lukasNo1** 2020-03-02 12:02 UTC
Labels: bug
